// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

	    int coinFlip = Integer.parseInt(args[0]);
		int lessThanHalf = 0;
		int moreThanHalf = 0;
		double ratio = 0;
		double rnd = 0;

		//flips the coin for the amount of times the user has entered
		for(; coinFlip > 0; coinFlip--){

			rnd = (double) Math.random();

			if(rnd > 0.5){
             moreThanHalf++;
			}
			else if(rnd <= 0.5){
				lessThanHalf++;
			}
		}

		System.out.println("> 0.5:  " + moreThanHalf + " times");
		System.out.println("<= 0.5: " + lessThanHalf + " times");

        int max = Math.max(lessThanHalf, moreThanHalf);
		int min = Math.min(lessThanHalf, moreThanHalf);
		//caculates the ratio and prints it
		if(max > 0 && min > 0){
			ratio = (double) min / max;
			System.out.print("Ratio:  " + ratio);
		}
	}
}
